on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC16F877A
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC16F877A
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/2cddec09c351a8cea49e6f97417b6709
          gist_title: Pr치ctica 7 - PWM PIC16F877A CCS.c
          gist_description: Pr치cticas PIC CCS
          github_file: Proyecto/PIC16F877A/PWM1.c
          file_encoding: WINDOWS-1252
    #PIC16F887
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC16F887
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/14726e9f3863b8ee7bdceeae645d446f
          gist_title: Pr치ctica 7 - PWM PIC16F887 CCS.c
          gist_description: Pr치cticas PIC CCS
          github_file: Proyecto/PIC16F887/PWM1.c
          file_encoding: WINDOWS-1252